# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Inserm u1001, Paris, France
email: xiaohu.song@inserm.fr
description: Robustness and evolvability of life
baseurl: "/u1001/" # the subpath of your site, e.g. /blog
#url: "https://maincover.github.io" # the base hostname & protocol for your site
repository: #https://github.com/eqxiu/eqxiu.github.io
twitter_username: xsong
github_username:  xsong

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
exclude: [node_modules, gulpfile.js]

# Pagination
paginate: 4
paginate_path: "page/:num"

gems:
 - jekyll-sitemap
 - jekyll-paginate